### ISSUE TITLE
Package Control

### ISSUE THREAD

**Issue by willsoto** [rafamds/OneDarkMaterial#1]
Any chance for this to be put up on [Package Control](https://packagecontrol.io/docs/submitting_a_package)? Nice theme

**Comment by rafmst** [comment]
Thanks @paradox41, 
I've already submitted my Pull Request to Package Control guys, we'll have to wait for their approval. :+1:

**Comment by willsoto** [comment]
Missed it when I looked. Excellent! Thank you.

**Comment by rafmst** [comment]
Don't forget to star if you enjoyed it, and feel free to report or suggest modifications ;)

**Comment by willsoto** [comment]
This was pulled in today. Closing
