### ISSUE TITLE
Issues with assets

### ISSUE THREAD

**Issue by willsoto** [rafamds/OneDarkMaterial#2]
After installing from Package Control, getting some issues with assets. Any suggestions?

<img width="1440" alt="screen shot 2015-10-18 at 12 33 53 pm" src="https://github-cloud.s3.amazonaws.com/assets/2791730/10565011/efd36626-7594-11e5-8e90-9723564a7188.png">

**Comment by agreco** [comment]
+1

**Comment by rafmst** [comment]
Yes, I got that too... I have to check what is wrong

**Comment by rafmst** [comment]
It should be working now
