### ISSUE TITLE
Black and white files icons

### ISSUE THREAD

**Issue by gerardroche** [rafamds/OneDarkMaterial#3]
re: https://github.com/equinusocio/material-theme/issues/324

**Comment by rafmst** [comment]
The only option is to create a theme modification like OneDarkMaterial and OneDarkMaterialDesaturated. Would you be interested in that option?

**Comment by gerardroche** [comment]
Probably not. I don't like the icons because I find them distracting. I like Atom's theme very much, particularly the tree view, right down to the line-height, colour, spacing, selected node background. It's nice. I also like that there are only a few different icons like for example markdown and images have their own icon. And the icons are high quality too. I would probably use a One Dark theme for ST if it was close enough to Atom's.

![atom](https://cloud.githubusercontent.com/assets/44148/10805805/89ea942e-7dc8-11e5-84cd-162665f4f4a3.png)

btw I use the Seti theme with icons disabled.

![seti](https://cloud.githubusercontent.com/assets/44148/10805841/cfeec33c-7dc8-11e5-8300-f55f790ae27f.png)

**Comment by rafmst** [comment]
Closed due to:

https://github.com/ptraceur/OneDarkMaterial/blob/master/README.md
