### ISSUE TITLE
Tab margin-top needs to be lower.

### ISSUE THREAD

**Issue by gobijan** [rafamds/OneDarkMaterial#4]
Great Theme!

Here is a screenshot comparing the tabs in ST3 OneDarkMaterial (left) and Atoms Theme (right):
![bildschirmfoto 2015-11-16 um 12 54 52](https://cloud.githubusercontent.com/assets/49339/11181313/5edcbf94-8c61-11e5-85f0-2a9813b799a3.png)

When in small sizes Atom removes the top margin from the tabs and when it is larger it uses smaller top-margin than in the OneDarkMaterial Theme:
![bildschirmfoto 2015-11-16 um 12 55 14](https://cloud.githubusercontent.com/assets/49339/11181344/924426e2-8c61-11e5-8e0a-1ebd799d43ea.png)

Also the Atom tabs make use of a little bit of inset shadow.

What do you think about adjusting this?

**Comment by rafmst** [comment]
I'll think about that. But for now, I can't promise you anything since I have more complex projects that need my attention. You can always do a pull request ;)

Thanks

**Comment by rafmst** [comment]
Closed due to:

https://github.com/ptraceur/OneDarkMaterial/blob/master/README.md
