### ISSUE TITLE
Folder pane does not styles..

### ISSUE THREAD

**Issue by yahyaerturan** [rafamds/OneDarkMaterial#5]
Great work, first of all. But folder pane is still default. I tried to open a new window and then add folder to project but still stands with default theme. Editor section is just great...

**Comment by rafmst** [comment]
Hi, and thanks. 
I'm not sure if I understand your problem correctly, could you please submit a screenshot?

Thanks again

**Comment by yahyaerturan** [comment]
I believe it is something related to my system. I reboot and reopen the sublime.. It works completely fine.. Sorry for bothering but at least I used to chance to thank you for the work.

**Comment by rafmst** [comment]
No problem at all :smile: have a nice day, and thanks again
