### ISSUE TITLE
Can you make the white background for Find a preference?

### ISSUE THREAD

**Issue by wesbaker** [rafamds/OneDarkMaterial#6]
The dark text on white background of Find is a bit jarring. Is there any way you could make that a preference?

![screen shot 2016-02-29 at 11 48 30 am](https://cloud.githubusercontent.com/assets/15715/13401510/5fa49a34-deda-11e5-8d50-01831623dc42.png)

**Comment by bbtfr** [comment]
I'd love to see that, too.

**Comment by rafmst** [comment]
Closed due to:

https://github.com/ptraceur/OneDarkMaterial/blob/master/README.md
