### ISSUE TITLE
Weird render

### ISSUE THREAD

**Issue by FlawaCLV** [rafamds/OneDarkMaterial#8]
I've followed your instructions but got some weird rendered colors...

<img width="1276" alt="capture d ecran 2016-09-09 a 14 06 36" src="https://cloud.githubusercontent.com/assets/4428764/18386330/a7440902-7696-11e6-8f95-9ea6c77535ab.png">

My configuration:
- Mac OS X El Capitan 10.11.6
- Sublime Text build 3114

**Comment by michaelfreund** [comment]
Same here

**Comment by rafmst** [comment]
Hi guys, I've abandoned this project. 
With my current work I couldn't keep up this project with the origin [material theme](https://github.com/equinusocio/material-theme).

You should install that instead, since its very customizable.

Thanks
